%---------------------------------------------------------
% Author : Mazen Alamir 
% CNRS, UNiversity of Grenoble-Alpes
% Gipsa Lab. Last modification March 2017
%---------------------------------------------------------

function sc=create_mv(p,pmin,pmax,alpha)
coder.allowpcode('plain');
np=length(p);cp=cell(1,np);
cpmin=cp;cpmax=cp;calpha=cp;
for i=1:np,
    c{i}=p(i);cpmin{i}=pmin(i);cpmax{i}=pmax(i);
    calpha{i}=alpha(i);
end
sc=struct(...
    'pmin',cpmin,'pmax',cpmax,'alpha',calpha,'p',c,...
    'beta_plus',2,'beta_moins',0.5,'alpha_min',1e-9,'param',[],...
    'pbarmin',c,'pbarmax',c,'pc',c,'beta',c,'Jpbarmin',c,...
    'gpbarmin',c,'Jpc',c,'gpc',c,'Jpbarmax',c,'gpbarmax',c,...
    'aJ',c,'bJ',c,'cJ',c,'ag',c,'bg',c,'cg',c,'ps_J',c,...
    'ps_J_star',c,'qJstar',c,'qJmin',c,'pJmin',c,'qJmax',c,...
    'pJmax',c,'ps_g',c,'ps_g_star',c,'qgstar',c,'qgmin',c,...
    'pgmin',c,'qgmax',c,'pgmax',c,'Z',zeros(4,1),'ngz',c);
return